### ISSUE TITLE
gulp failure

### ISSUE THREAD

**Issue by golfecholima** [Quartz/Chartbuilder#201]
`npm run dev` fails at gulp:

```
$ npm run dev

> chartbuilder@2.2.0 dev /Users/workmcgerk/Desktop/repos/Chartbuilder-qz
> gulp

[11:17:50] Using gulpfile ~/Desktop/repos/Chartbuilder-qz/gulpfile.js
[11:17:50] Starting 'clean'...
[11:17:50] Finished 'clean' after 3.66 ms
[11:17:50] Starting 'default'...
[11:17:50] Starting 'browserify:dev'...
[11:17:50] Starting 'stylus'...
[11:17:50] Starting 'copy-htdocs'...
[11:17:50] Starting 'copy-fonts'...
[11:17:50] Starting 'copy-assets'...
[11:17:50] Finished 'default' after 23 ms
[11:17:50] Finished 'copy-fonts' after 15 ms
[11:17:50] Finished 'copy-assets' after 519 ms
[11:17:50] Finished 'copy-htdocs' after 532 ms
[11:17:51] Finished 'stylus' after 1.57 s
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

Error: module "react-addons-pure-render-mixin" not found from "/Users/workmcgerk/Desktop/repos/Chartbuilder-qz/src/js/components/ChartMetadata.jsx"
    at notFound (/Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/index.js:803:15)
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/index.js:754:23
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/browser-resolve/index.js:185:24
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:44:14
    at process (/Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:113:43)
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:122:21
    at load (/Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:54:43)
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:60:22
    at /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/node_modules/browserify/node_modules/resolve/lib/async.js:16:47
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! chartbuilder@2.2.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chartbuilder@2.2.0 dev script 'gulp'.
npm ERR! This is most likely a problem with the chartbuilder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get their info via:
npm ERR!     npm owner ls chartbuilder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/workmcgerk/Desktop/repos/Chartbuilder-qz/npm-debug.log
```

**Comment by yanofsky** [comment]
Did you run `npm install` After merging?

You're missing the `react-addons-pure-render-mixin` package

**Comment by nsonnad** [comment]
Looks like it was missing from `package.json`. I added it here: https://github.com/Quartz/Chartbuilder/commit/1d324dfc104585e74ff7f14f49d940252b45c0fa

Try pulling and re-running `npm install`

**Comment by chagan** [comment]
Excellent timing. Had the same issue and this worked for me.

**Comment by golfecholima** [comment]
huzzah! thanks @nsonnad & @yanofsky

**Comment by yanofsky** [comment]
Sorry for the bug, thanks @nsonnad for fixing
